parameters:

services:
    Overblog\GraphQL\Bundle\ConfigurationYamlXmlBundle\ConfigurationXmlParser:
        arguments:
            - "%graphql.configuration.directories.xml%"
        tags:
            - { name: "overblog_graphql.configuration.provider" }
