parameters:

services:
    Overblog\GraphQL\Bundle\ConfigurationXmlBundle\ConfigurationXmlParser:
        arguments:
            - '%graphql.configuration.directories.xml%'
        tags:
            - { name: 'overblog_graphql.configuration.provider' }
